/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
/**
 *
 * @author miguel_a_andrade
 */
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import net.objecthunter.exp4j.Expression;
import net.objecthunter.exp4j.ExpressionBuilder;

public class TelaPrincipal extends javax.swing.JFrame {
       
    /**
     * Creates new form TelaPrincipal
     */
    
    private String visorEquacoes = ""; // Variavel para valor atual do visor de forma global; //
    private String equacaoParaSalvar = ""; // Variavel para a equação completa com resultado para ser salva; //
    
   // Metodo calculo() para lidar com a equação em formato de String seguindo a logica de como a equação deve ser calculada usando Exp4j que é uma biblioteca para expressões matematicas; //
    private double calculo(){
        
        //Achei a biblioteca Exp4j nesse link -> https://stackoverflow.com/questions/7258538/method-for-evaluating-math-expressions-in-java  ;//
        
        visorEquacoes = visorEquacoes.replace('÷', '/'); // Retirar todos os '÷' e colocar '/' no lugar para devido calculo do Exp4j; //
        visorEquacoes = visorEquacoes.replace('x', '*'); // Retirar todos os 'x' e colocar '*' no lugar para devido calculo do Exp4j; //
        
        // Criando a expressão com Exp4j; com base nesse link -> https://www.objecthunter.net/exp4j/apidocs/net/objecthunter/exp4j/ExpressionBuilder.html e https://stackoverflow.com/questions/7258538/method-for-evaluating-math-expressions-in-java  //
        Expression expressao = new ExpressionBuilder(visorEquacoes).build();
        //  Cria uma instância de Expression(Expressão matematica construida)usando o build a partir da string que representa a expressão matemática; //

        //  Retorna resultado do metódo evaluate() que pertence a classe Expression para calcular o valor da expressão onde irá retornar um double; //
        return expressao.evaluate();
    }
    
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jbtIgual = new javax.swing.JButton();
        jbtMemoria = new javax.swing.JButton();
        jbtDecimal = new javax.swing.JButton();
        jbtBotao1 = new javax.swing.JButton();
        jbtBotao2 = new javax.swing.JButton();
        jbtBotao3 = new javax.swing.JButton();
        jbtSubtracao = new javax.swing.JButton();
        jbtBotao0 = new javax.swing.JButton();
        jbtBotao5 = new javax.swing.JButton();
        jbtBotao4 = new javax.swing.JButton();
        jbtBotao7 = new javax.swing.JButton();
        jbtBotao8 = new javax.swing.JButton();
        jbtBotao9 = new javax.swing.JButton();
        jbtAdicao = new javax.swing.JButton();
        jbtDivisao = new javax.swing.JButton();
        jbtMultiplicacao = new javax.swing.JButton();
        jbtCE = new javax.swing.JButton();
        jbtApagar = new javax.swing.JButton();
        jbtArmazenarMemoria = new javax.swing.JButton();
        jbtResto = new javax.swing.JButton();
        jbtBotao6 = new javax.swing.JButton();
        jtfVisor = new javax.swing.JTextField();
        jbtMemoriaClear = new javax.swing.JButton();
        jmbPrincipal = new javax.swing.JMenuBar();
        jmbConversor = new javax.swing.JMenu();
        jmbCoversorDeVelocidade = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(309, 370));
        setPreferredSize(new java.awt.Dimension(309, 340));
        setResizable(false);
        setSize(new java.awt.Dimension(309, 400));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jbtIgual.setBackground(new java.awt.Color(102, 255, 102));
        jbtIgual.setForeground(new java.awt.Color(255, 255, 255));
        jbtIgual.setText("=");
        jbtIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtIgualActionPerformed(evt);
            }
        });

        jbtMemoria.setBackground(new java.awt.Color(204, 204, 204));
        jbtMemoria.setText("Memória");
        jbtMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMemoriaActionPerformed(evt);
            }
        });

        jbtDecimal.setBackground(new java.awt.Color(153, 153, 153));
        jbtDecimal.setForeground(new java.awt.Color(255, 255, 255));
        jbtDecimal.setText(".");
        jbtDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDecimalActionPerformed(evt);
            }
        });

        jbtBotao1.setBackground(new java.awt.Color(255, 204, 0));
        jbtBotao1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtBotao1.setForeground(new java.awt.Color(255, 255, 255));
        jbtBotao1.setText("1");
        jbtBotao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBotao1ActionPerformed(evt);
            }
        });

        jbtBotao2.setBackground(new java.awt.Color(255, 204, 0));
        jbtBotao2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtBotao2.setForeground(new java.awt.Color(255, 255, 255));
        jbtBotao2.setText("2");
        jbtBotao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBotao2ActionPerformed(evt);
            }
        });

        jbtBotao3.setBackground(new java.awt.Color(255, 204, 0));
        jbtBotao3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtBotao3.setForeground(new java.awt.Color(255, 255, 255));
        jbtBotao3.setText("3");
        jbtBotao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBotao3ActionPerformed(evt);
            }
        });

        jbtSubtracao.setBackground(new java.awt.Color(153, 153, 153));
        jbtSubtracao.setForeground(new java.awt.Color(255, 255, 255));
        jbtSubtracao.setText("-");
        jbtSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSubtracaoActionPerformed(evt);
            }
        });

        jbtBotao0.setBackground(new java.awt.Color(102, 102, 102));
        jbtBotao0.setForeground(new java.awt.Color(255, 255, 255));
        jbtBotao0.setText("0");
        jbtBotao0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBotao0ActionPerformed(evt);
            }
        });

        jbtBotao5.setBackground(new java.awt.Color(255, 204, 0));
        jbtBotao5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtBotao5.setForeground(new java.awt.Color(255, 255, 255));
        jbtBotao5.setText("5");
        jbtBotao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBotao5ActionPerformed(evt);
            }
        });

        jbtBotao4.setBackground(new java.awt.Color(255, 204, 0));
        jbtBotao4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtBotao4.setForeground(new java.awt.Color(255, 255, 255));
        jbtBotao4.setText("4");
        jbtBotao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBotao4ActionPerformed(evt);
            }
        });

        jbtBotao7.setBackground(new java.awt.Color(255, 204, 0));
        jbtBotao7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtBotao7.setForeground(new java.awt.Color(255, 255, 255));
        jbtBotao7.setText("7");
        jbtBotao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBotao7ActionPerformed(evt);
            }
        });

        jbtBotao8.setBackground(new java.awt.Color(255, 204, 0));
        jbtBotao8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtBotao8.setForeground(new java.awt.Color(255, 255, 255));
        jbtBotao8.setText("8");
        jbtBotao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBotao8ActionPerformed(evt);
            }
        });

        jbtBotao9.setBackground(new java.awt.Color(255, 204, 0));
        jbtBotao9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtBotao9.setForeground(new java.awt.Color(255, 255, 255));
        jbtBotao9.setText("9");
        jbtBotao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBotao9ActionPerformed(evt);
            }
        });

        jbtAdicao.setBackground(new java.awt.Color(153, 153, 153));
        jbtAdicao.setForeground(new java.awt.Color(255, 255, 255));
        jbtAdicao.setText("+");
        jbtAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAdicaoActionPerformed(evt);
            }
        });

        jbtDivisao.setBackground(new java.awt.Color(153, 153, 153));
        jbtDivisao.setForeground(new java.awt.Color(255, 255, 255));
        jbtDivisao.setText("÷");
        jbtDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDivisaoActionPerformed(evt);
            }
        });

        jbtMultiplicacao.setBackground(new java.awt.Color(153, 153, 153));
        jbtMultiplicacao.setForeground(new java.awt.Color(255, 255, 255));
        jbtMultiplicacao.setText("x");
        jbtMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMultiplicacaoActionPerformed(evt);
            }
        });

        jbtCE.setBackground(new java.awt.Color(255, 0, 0));
        jbtCE.setForeground(new java.awt.Color(255, 255, 255));
        jbtCE.setText("CE");
        jbtCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCEActionPerformed(evt);
            }
        });

        jbtApagar.setBackground(new java.awt.Color(255, 102, 102));
        jbtApagar.setForeground(new java.awt.Color(255, 255, 255));
        jbtApagar.setText("<-");
        jbtApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtApagarActionPerformed(evt);
            }
        });

        jbtArmazenarMemoria.setBackground(new java.awt.Color(102, 102, 102));
        jbtArmazenarMemoria.setForeground(new java.awt.Color(255, 255, 255));
        jbtArmazenarMemoria.setText("M+");
        jbtArmazenarMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtArmazenarMemoriaActionPerformed(evt);
            }
        });

        jbtResto.setBackground(new java.awt.Color(153, 153, 153));
        jbtResto.setForeground(new java.awt.Color(255, 255, 255));
        jbtResto.setText("%");
        jbtResto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRestoActionPerformed(evt);
            }
        });

        jbtBotao6.setBackground(new java.awt.Color(255, 204, 0));
        jbtBotao6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtBotao6.setForeground(new java.awt.Color(255, 255, 255));
        jbtBotao6.setText("6");
        jbtBotao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBotao6ActionPerformed(evt);
            }
        });

        jtfVisor.setEditable(false);
        jtfVisor.setBackground(new java.awt.Color(102, 102, 102));
        jtfVisor.setFont(new java.awt.Font("Microsoft YaHei", 0, 26)); // NOI18N
        jtfVisor.setForeground(new java.awt.Color(255, 255, 255));
        jtfVisor.setToolTipText("");
        jtfVisor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jtfVisor.setMargin(new java.awt.Insets(2, 20, 2, 6));
        jtfVisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfVisorActionPerformed(evt);
            }
        });

        jbtMemoriaClear.setBackground(new java.awt.Color(102, 102, 102));
        jbtMemoriaClear.setForeground(new java.awt.Color(255, 255, 255));
        jbtMemoriaClear.setText("MC");
        jbtMemoriaClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMemoriaClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jbtBotao7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtBotao8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jbtBotao4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtBotao5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbtBotao9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtBotao6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jbtBotao1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtBotao2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtBotao3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtAdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtSubtracao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtDivisao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jtfVisor)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jbtCE, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtArmazenarMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtMemoriaClear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtMultiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jbtMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jbtBotao0, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtDecimal, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtResto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtMultiplicacao)
                    .addComponent(jbtCE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtArmazenarMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtMemoriaClear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jbtAdicao)
                        .addGap(12, 12, 12)
                        .addComponent(jbtSubtracao))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtBotao7)
                            .addComponent(jbtBotao8)
                            .addComponent(jbtBotao9)
                            .addComponent(jbtDivisao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtBotao6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbtBotao5)
                                .addComponent(jbtBotao4)))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtBotao3)
                            .addComponent(jbtBotao2)
                            .addComponent(jbtBotao1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtBotao0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtDecimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtResto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtMemoria)
                    .addComponent(jbtIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        jmbConversor.setText("Conversor");

        jmbCoversorDeVelocidade.setText("Conversor");
        jmbCoversorDeVelocidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbCoversorDeVelocidadeActionPerformed(evt);
            }
        });
        jmbConversor.add(jmbCoversorDeVelocidade);

        jmbPrincipal.add(jmbConversor);

        jMenu2.setText("Sair");
        jmbPrincipal.add(jMenu2);

        setJMenuBar(jmbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 334, 313);
    }// </editor-fold>//GEN-END:initComponents

    private void jmbCoversorDeVelocidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbCoversorDeVelocidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmbCoversorDeVelocidadeActionPerformed

    private void jtfVisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfVisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfVisorActionPerformed

    private void jbtBotao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBotao6ActionPerformed
        // TODO add your handling code here:
        visorEquacoes += "6"; // Atualiza a variavel global acrescentando o digito do botão; //
        jtfVisor.setText(visorEquacoes);// Insere o texto no visor a partir da string de variavel global; //
    }//GEN-LAST:event_jbtBotao6ActionPerformed

    private void jbtApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtApagarActionPerformed
        // TODO add your handling code here:
        String stringVisor = jtfVisor.getText(); // Cria uma String stringVisor para salvar o valor do texto atual do Visor; //
        int tamanho = stringVisor.length(); // Cria um int para salvar o tamanho do stringVisor; //
        stringVisor = stringVisor.substring(0, tamanho - 1); // Salva o resultado da substring para o stringVisor, substring feita começando do indice 0 do stringVisor, até o tamanho -1 (removendo ultimo caracter; //
        visorEquacoes = stringVisor; // Atualiza variavel global para valor do stringVisor com um caracter removido; //
        jtfVisor.setText(visorEquacoes); // Insere texto da variavel global no visor; //
    }//GEN-LAST:event_jbtApagarActionPerformed

    private void jbtCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCEActionPerformed
        // TODO add your handling code here:
        visorEquacoes = ""; // Apaga o valor da varivael global; //
        jtfVisor.setText(visorEquacoes); // Insere texto da variavel global no visor; //
    }//GEN-LAST:event_jbtCEActionPerformed

    private void jbtMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMultiplicacaoActionPerformed
        // TODO add your handling code here:
        visorEquacoes = jtfVisor.getText()+" x "; // Atualiza variavel global, pegando o texto do visor adicionando o " x "; //
        jtfVisor.setText(visorEquacoes); // Insere texto da variavel global no visor; //
    }//GEN-LAST:event_jbtMultiplicacaoActionPerformed

    private void jbtDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDivisaoActionPerformed
        // TODO add your handling code here:
        visorEquacoes = jtfVisor.getText()+" ÷ "; // Atualiza variavel global, pegando o texto do visor adicionando o " ÷ "; //
        jtfVisor.setText(visorEquacoes); // Insere texto da variavel global no visor; //
    }//GEN-LAST:event_jbtDivisaoActionPerformed

    private void jbtAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAdicaoActionPerformed
        // TODO add your handling code here:
        visorEquacoes = jtfVisor.getText()+" + "; // Atualiza variavel global, pegando o texto do visor adicionando o " + "; //
        jtfVisor.setText(visorEquacoes); // Insere texto da variavel global no visor; //
    }//GEN-LAST:event_jbtAdicaoActionPerformed

    private void jbtBotao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBotao9ActionPerformed
        // TODO add your handling code here:
        visorEquacoes += "9"; // Atualiza a variavel global acrescentando o digito do botão; //
        jtfVisor.setText(visorEquacoes); // Insere texto da variavel global no visor; //
    }//GEN-LAST:event_jbtBotao9ActionPerformed

    private void jbtBotao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBotao8ActionPerformed
        // TODO add your handling code here:
        visorEquacoes += "8"; // Atualiza a variavel global acrescentando o digito do botão; //
        jtfVisor.setText(visorEquacoes); // Insere texto da variavel global no visor; //
    }//GEN-LAST:event_jbtBotao8ActionPerformed

    private void jbtBotao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBotao7ActionPerformed
        // TODO add your handling code here:
        visorEquacoes += "7"; // Atualiza a variavel global acrescentando o digito do botão; //
        jtfVisor.setText(visorEquacoes); // Insere texto da variavel global no visor; //
    }//GEN-LAST:event_jbtBotao7ActionPerformed

    private void jbtBotao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBotao4ActionPerformed
        // TODO add your handling code here:
        visorEquacoes += "4"; // Atualiza a variavel global acrescentando o digito do botão; //
        jtfVisor.setText(visorEquacoes); // Insere texto da variavel global no visor; //
    }//GEN-LAST:event_jbtBotao4ActionPerformed

    private void jbtBotao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBotao5ActionPerformed
        // TODO add your handling code here:
        visorEquacoes += "5"; // Atualiza a variavel global acrescentando o digito do botão; //
        jtfVisor.setText(visorEquacoes); // Insere texto da variavel global no visor; //
    }//GEN-LAST:event_jbtBotao5ActionPerformed

    private void jbtBotao0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBotao0ActionPerformed
        // TODO add your handling code here:
        visorEquacoes += "0"; // Atualiza a variavel global acrescentando o digito do botão; //
        jtfVisor.setText(visorEquacoes); // Insere texto da variavel global no visor; //
    }//GEN-LAST:event_jbtBotao0ActionPerformed

    private void jbtSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSubtracaoActionPerformed
        // TODO add your handling code here:
        visorEquacoes = jtfVisor.getText()+" - "; // Atualiza variavel global, pegando o texto do visor adicionando o " - "; //
        jtfVisor.setText(visorEquacoes); // Insere texto da variavel global no visor; //
    }//GEN-LAST:event_jbtSubtracaoActionPerformed

    private void jbtBotao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBotao3ActionPerformed
        // TODO add your handling code here:
        visorEquacoes += "3"; // Atualiza a variavel global acrescentando o digito do botão; //
        jtfVisor.setText(visorEquacoes); // Insere texto da variavel global no visor; //
    }//GEN-LAST:event_jbtBotao3ActionPerformed

    private void jbtBotao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBotao2ActionPerformed
        // TODO add your handling code here:
        visorEquacoes += "2"; // Atualiza a variavel global acrescentando o digito do botão; //
        jtfVisor.setText(visorEquacoes); // Insere texto da variavel global no visor; //
    }//GEN-LAST:event_jbtBotao2ActionPerformed

    private void jbtBotao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBotao1ActionPerformed
        // TODO add your handling code here:
        visorEquacoes += "1"; // Atualiza a variavel global acrescentando o digito do botão; //
        jtfVisor.setText(visorEquacoes); // Insere texto da variavel global no visor; //
    }//GEN-LAST:event_jbtBotao1ActionPerformed

    private void jbtDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDecimalActionPerformed
        // TODO add your handling code here:
        visorEquacoes += "."; // Atualiza a variavel global acrescentando o digito do botão; //
        jtfVisor.setText(visorEquacoes); // Insere texto da variavel global no visor; //
    }//GEN-LAST:event_jbtDecimalActionPerformed

    private void jbtIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIgualActionPerformed
        // TODO add your handling code here:
        try {
            // Tenta usar o metodo calculo() para calcular e exibir o resultado da expressão matematica em formato de string, salvando toda a equação na variavel global "equacaoParaSalvar"; //
            equacaoParaSalvar = jtfVisor.getText();
            jtfVisor.setText(Double.toString(calculo()));
            equacaoParaSalvar += " = "+Double.toString(calculo());
        } catch (Exception e) {
            // Se equacoes() falhar, mostra a mensagem de erro no visor; //
            jtfVisor.setText("Erro na sintaxe");
        } finally {
            // Falhando ou não a variavel global terá seu valor igual a ""; //
            visorEquacoes = "";
        }
    }//GEN-LAST:event_jbtIgualActionPerformed

    private void jbtArmazenarMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtArmazenarMemoriaActionPerformed
        // TODO add your handling code here:
        if(equacaoParaSalvar.isEmpty()){ // Verifica se a equacaoParaSalvar está vazia; //
            // Se estiver vazia, mostra o paneil do JOption informando a falta de equação para ser salva; //
            JOptionPane.showMessageDialog(null, "Não há equação para ser salva!");
        }else { // Se equacaoParaSalvar não estiver vazia; //
            try (PrintWriter gravadorMemoria = new PrintWriter(new FileWriter("memoria.txt", true))) {
                // Cria um novo PrintWriter gravadorMemoria(Permite escrever strings e outras formas de saída facilmente) que será usado para escrever no arquivo "memoria.txt"; //
                // O FileWriter abre o arquivo memoria.txt para escrita e o segundo argumento 'true' no FileWriter significa que estrá sendo aberto o arquivo no modo de anexo (append); //
                // Usando o modo de anexo ( como segundo argumento em "true") , irá fazer o novo conteúdo ser adicionado ao final do arquivo sem sobrescrever o conteúdo que já existe; //
                
                gravadorMemoria.println(equacaoParaSalvar); // Escreve a equação que está como String no arquivo, adicionando uma nova linha no final; //
                
                JOptionPane.showMessageDialog(null, "A equação: "+equacaoParaSalvar+" foi salva com sucesso!"); // Exibe um painel JOption para informar que a equação foi salva com sucesso; //
            } catch (IOException e) { // Caso falhar exibe um painel JOption com a mensagem de erro; //
                JOptionPane.showMessageDialog(null, "Erro ao salvar o arquivo: " + e.getMessage());
            } finally { // Limpa a equacaoParaSalvar falhando ou não; //
                equacaoParaSalvar = "";
            }
        }
    }//GEN-LAST:event_jbtArmazenarMemoriaActionPerformed

    private void jbtRestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRestoActionPerformed
        // TODO add your handling code here:
        visorEquacoes = jtfVisor.getText()+" % "; // Atualiza variavel global, pegando o texto do visor adicionando o " % "; //
        jtfVisor.setText(visorEquacoes); // Insere texto da variavel global no visor; //
    }//GEN-LAST:event_jbtRestoActionPerformed

    private void jbtMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMemoriaActionPerformed
        // TODO add your handling code here:
        // Cria uma instância de StringBuilder, onde é usada para construir uma string de forma eficiente, permitindo concatenar várias strings sem criar novos objetos para cada operaçã; //
            StringBuilder conteudo = new StringBuilder();
            
            // Adiciona o texto: "Memória da Calculadora" ao StringBuilder; //
            conteudo = conteudo.append("======Memoria da Calculadora======\n-----------------------------"
                    + "--------------------------\n");
    
        try (BufferedReader leitor = new BufferedReader(new FileReader("memoria.txt"))) {
            // Faz um Try Catch tentando instanciar um BufferedReader leitor, usando o arquivo memoria.txt para ser lido; //
            // O BufferedReader é utilizado para ler o arquivo de forma eficiente, especialmente ao ler linha por linha;//
            
            // Inicializa uma variável para armazenar as linhas lidas do arquivo; //
            String linha;
            
            // Loop para ler cada linha do arquivo "memoria.txt" até que não haja mais linhas; //
            while ((linha = leitor.readLine()) != null) {
                
            // Adiciona a linha lida ao StringBuilder, seguida por uma nova linha e um separador; //
                conteudo.append(linha).append("\n").append("-----------------------"
                        + "--------------------------------\n");
            }
        } catch (IOException e) { // Se occorer uma falha; //
            // Exibe uma caixa de diálogo de alerta com a mensagem de erro; //
            JOptionPane.showMessageDialog(null, "Erro ao ler o arquivo: " + e.getMessage());
            return;
        }
    
        // Exibe o conteúdo do arquivo em um JOptionPane; //
        JOptionPane.showMessageDialog(null, conteudo.toString());
    }//GEN-LAST:event_jbtMemoriaActionPerformed

    private void jbtMemoriaClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMemoriaClearActionPerformed
        // TODO add your handling code here:
        try (FileWriter escritor = new FileWriter("memoria.txt", false)) {
            // Escreve no arquivo memoria.txt nada, o tornando vazio e assim "deletado"; //
            
            // Informa se houve o sucesso ao limpar memoria; //
            JOptionPane.showMessageDialog(null, "A memoria foi limpada com sucesso!!");
        } catch (IOException e) { // Caso não; //
            // Exibe uma caixa de diálogo de alerta com a mensagem de erro
            JOptionPane.showMessageDialog(null, "Erro ao limpar o arquivo: " + e.getMessage());
        }
    }//GEN-LAST:event_jbtMemoriaClearActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jbtAdicao;
    private javax.swing.JButton jbtApagar;
    private javax.swing.JButton jbtArmazenarMemoria;
    private javax.swing.JButton jbtBotao0;
    private javax.swing.JButton jbtBotao1;
    private javax.swing.JButton jbtBotao2;
    private javax.swing.JButton jbtBotao3;
    private javax.swing.JButton jbtBotao4;
    private javax.swing.JButton jbtBotao5;
    private javax.swing.JButton jbtBotao6;
    private javax.swing.JButton jbtBotao7;
    private javax.swing.JButton jbtBotao8;
    private javax.swing.JButton jbtBotao9;
    private javax.swing.JButton jbtCE;
    private javax.swing.JButton jbtDecimal;
    private javax.swing.JButton jbtDivisao;
    private javax.swing.JButton jbtIgual;
    private javax.swing.JButton jbtMemoria;
    private javax.swing.JButton jbtMemoriaClear;
    private javax.swing.JButton jbtMultiplicacao;
    private javax.swing.JButton jbtResto;
    private javax.swing.JButton jbtSubtracao;
    private javax.swing.JMenu jmbConversor;
    private javax.swing.JMenuItem jmbCoversorDeVelocidade;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JTextField jtfVisor;
    // End of variables declaration//GEN-END:variables
}
